baseURL = "https://sunboxlabs.com/"
languageCode = "en-us"
Title = "sunboxlabs"
Subtitle = "DIY Solar Generator How-to guides and kits"
summaryLength = 25
copyright = "sunboxlabs.com is a participant in the Amazon Services LLC Associates Program, an affiliate advertising program designed to provide a means for sites to earn advertising fees by advertising and linking to amazon.com."
enableEmoji = true
publishDir = "docs"
disqusShortname = "sunboxlabs"
googleAnalytics = "UA-103591436-1"

[markup.goldmark.renderer]
  unsafe= true

  [author]
    name = "Niko"

[params]

  [params.publisher]
    name = "sunboxlabs"

    [params.publisher.logo]
      url = "/img/sarah_spinning_sun.png"
      width = 50
      height = 50

  [params.logo]
    url = "/img/logo.png"
    width = 200
    height = 200

  [params.image]
    url = "/img/bg-masthead.jpg"
    width = 1360
    height = 751


[[Site.params]]
  title = "sunboxlabs"
  description ="Sunboxlabs - The best portable solar generator kits for backup or fun."
  #mailchimp = "you can provide a mailchimp-link here"

## Main Menu
[[menu.main]]
    name = "Guides"
    identifier = "guides"
    weight = 200
    url = "/"

[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 200
    url = "/about"

[[menu.main]]
    name = "Contact"
    identifier = "contact"
    url = "/contact"

[[menu.main]]
    name = "500W Solar Kit"
    identifier = "buy"
    url = "/solar-kit"

[[menu.main]]
    name = "300W Solar Kit"
    identifier = "buy300"
    url = "/solar-kit-300"
